-   id: validate_manifest
    name: validate reformat manifest
    description: This validator validates a reformat hooks manifest file
    entry: reformat-validate-manifest
    language: python
    files: ^(\.reformat-hooks\.yaml|hooks\.yaml)$
